### ISSUE TITLE
Using "go test" flags causes multiconfig to exit with a non-zero status

### ISSUE THREAD

**Issue by four2five** [koding/multiconfig#40]
The issue appears to be caused by "go test" passing its flags (with some reformatting, like -v turning into -test.v) to the test code and multiconfig is concerned because it is unaware of those flags.

I've pushed a branch with code that demonstrates the issue: https://github.com/four2five/gotest_multiconfig_example

**Comment by four2five** [comment]
Actually, an even easier reproduction case is to simply run "go test -v" on master.

**Comment by cihangir** [comment]
hi @four2five thanks for opening the issue, would you like to help us on resolving the issue?

**Comment by four2five** [comment]
@cihangir Sure thing. I'd be happy to pitch in as we would like to use a version of viper with this issue resolved. What would you  like me to do?

**Comment by four2five** [comment]
@cihangir I'm doubt that I'll be able to find time in the near term as I've sorted out an alternative solution for our pressing need. Best Regards.

**Comment by cihangir** [comment]
Since this is not an problem for us closing this issue

**Comment by gertcuykens** [comment]
Huge problem for me doh because the Jenkins not in my control uses `go test -v` so the solution to flag.Set("test.v", "true") will still cause the Jenkins test to fail. Kan there maybe be a few lines of code added to discard everything starting with `test.*`?
