### ISSUE TITLE
panic: not struct

### ISSUE THREAD

**Issue by jonaz** [koding/multiconfig#48]
@cihangir commit 15a9baf17e5dc67025d30dd65c98bb7e2edc3dd1 seems to have introduced a bug. 

```
panic: not struct

goroutine 1 [running]:
panic(0x8ff0a0, 0xc820202b90)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/fatih/structs.strctVal(0x8d8520, 0xc8201cb3b0, 0x0, 0x0, 0x0)
	/home/jonaz/go/src/github.com/fatih/structs/structs.go:439 +0x138
github.com/fatih/structs.(*Field).FieldOk(0xc8201dc6c0, 0xc82020295c, 0x4, 0x3, 0xa0a840)
	/home/jonaz/go/src/github.com/fatih/structs/field.go:129 +0x107
github.com/fatih/structs.(*Field).Field(0xc8201dc6c0, 0xc82020295c, 0x4, 0xad1120)
	/home/jonaz/go/src/github.com/fatih/structs/field.go:109 +0x39
github.com/koding/multiconfig.(*EnvironmentLoader).processField(0xc8201fe880, 0xadd680, 0xc, 0xc8201dc6c0, 0xad1120, 0xa, 0x8fdba0, 0xc8201d2090, 0x0, 0x0)
	/home/jonaz/go/src/github.com/koding/multiconfig/env.go:61 +0x1da
github.com/koding/multiconfig.(*EnvironmentLoader).Load(0xc8201fe880, 0x8d2160, 0xc8201cb3b0, 0x0, 0x0)
	/home/jonaz/go/src/github.com/koding/multiconfig/env.go:45 +0x1bd
github.com/koding/multiconfig.multiLoader.Load(0xc8201f2fc0, 0x4, 0x4, 0x8d2160, 0xc8201cb3b0, 0x0, 0x0)
	/home/jonaz/go/src/github.com/koding/multiconfig/multiloader.go:14 +0xc6
github.com/koding/multiconfig.(*multiLoader).Load(0xc8201fe8a0, 0x8d2160, 0xc8201cb3b0, 0x0, 0x0)
	<autogenerated>:7 +0xc1
github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/notifications.(*router).Load(0xc8201d20f0, 0xb3b9a0, 0x12, 0x0, 0x0)
	/home/jonaz/go/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/notifications/router.go:49 +0x210

```

multiconfig is used here:
https://github.com/stampzilla/stampzilla-go/blob/master/nodes/stampzilla-server/notifications/router.go#L49

If you need more than that please say and i'll put together a runnable example.

**Comment by cihangir** [comment]
Hi @jonaz i took a look at what is wrong here but could not find a problem, because the maps you are sending into decoder are not in fact [structs](https://github.com/stampzilla/stampzilla-go/commit/9d6d0b2d3b0600460d23b824dabca54821f4f2ed), so it is intended behaviour, Previously it was broken. Sorry but our bug was your feature.

Let me know if you have another take on that. Thanks for the issue.

**Comment by client9** [comment]
Either multiconfig is failing silently when maps are used, or maps are working minus help.  Seems like it should fail immediately if a map is used, or -help should be fixed.

**Comment by cihangir** [comment]
@client9 you are right, we should fail immediately
