### ISSUE TITLE
is it right? thanks

### ISSUE THREAD

**Issue by icoder528** [koding/multiconfig#63]
code:
func main() {
	var cfg = struct {
		Name string \`\`
		Age  int    \`default:"30"\`
	}{"Lily", 29}
	multiconfig.MustLoadWithPath("config.toml", &cfg)
	fmt.Println(cfg)
}
config:
name = "Tom"`
****************************************
the result is "{Tom 30}"，I expected cfg's Age is 29, I think cfg's Age will be 30 when not initialized

**Comment by rjeczalik** [comment]
Hey @icoder528! The `default` tag overwrites any value that the struct field was initialised with. This is by design.
