### ISSUE TITLE
Comma separated lists in YAML

### ISSUE THREAD

**Issue by ilithium** [koding/multiconfig#64]
Hi

I've just discovered a minor flag in the YAML implementation.

In my yaml file, I have:

```
somekey: a,b,c,d,e,f
```

and in my struct, I have:

```
type test struct {
SomeKey []string
}
```

The YAML is officially valid, but causes a parse error

**Comment by rjeczalik** [comment]
Hey @ilithium, multiconfig uses `gopkg.in/yaml.v2` for YAML parsing, you may want to report this issue upstrea - https://github.com/go-yaml/yaml.
